export { getAssessmentModel } from './assessment.js';
export { getBidProfileModel } from './bidProfile.js';
export { getFaqModel } from './faq.js';
export { getConsumptionAccountModel } from './consumptionAccount.js';
export { getConsumptionLedgerEntryModel } from './consumptionLedgerEntry.js';
export { getConsumptionTransactionModel } from './consumptionTransaction.js';
export { getInterviewLogModel } from './interviewLog.js';
export { getInterviewModel } from './interview.js';
export { getJobBidModel } from './jobBid.js';
export { getMarketplaceCallerProfileModel } from './marketplaceCallerProfile.js';
export { getMarketplaceInterviewOpportunityModel } from './marketplaceInterviewOpportunity.js';
export { getMarketplaceMatchModel } from './marketplaceMatch.js';
export { getMarketplaceParticipantModel } from './marketplaceParticipant.js';
export { getProfileShareRequestModel } from './profileShareRequest.js';
export { getScrapedJobModel } from './scrapedJob.js';
export { getTailoredResumeModel } from './tailoredResume.js';
export { getTeamConsumptionModel } from './teamConsumption.js';
export { getWebUserModel } from './webUser.js';

import { getAssessmentModel } from './assessment.js';
import { getBidProfileModel } from './bidProfile.js';
import { getFaqModel } from './faq.js';
import { getConsumptionAccountModel } from './consumptionAccount.js';
import { getConsumptionLedgerEntryModel } from './consumptionLedgerEntry.js';
import { getConsumptionTransactionModel } from './consumptionTransaction.js';
import { getInterviewLogModel } from './interviewLog.js';
import { getInterviewModel } from './interview.js';
import { getJobBidModel } from './jobBid.js';
import { getMarketplaceCallerProfileModel } from './marketplaceCallerProfile.js';
import { getMarketplaceInterviewOpportunityModel } from './marketplaceInterviewOpportunity.js';
import { getMarketplaceMatchModel } from './marketplaceMatch.js';
import { getMarketplaceParticipantModel } from './marketplaceParticipant.js';
import { getProfileShareRequestModel } from './profileShareRequest.js';
import { getScrapedJobModel } from './scrapedJob.js';
import { getTailoredResumeModel } from './tailoredResume.js';
import { getTeamConsumptionModel } from './teamConsumption.js';
import { getWebUserModel } from './webUser.js';

export function setupWebAssociations() {
  const WebUserModel = getWebUserModel();
  const ScrapedJobModel = getScrapedJobModel();
  const BidProfileModel = getBidProfileModel();
  const AssessmentModel = getAssessmentModel();
  const FaqModel = getFaqModel();
  const ConsumptionAccountModel = getConsumptionAccountModel();
  const ConsumptionLedgerEntryModel = getConsumptionLedgerEntryModel();
  const ConsumptionTransactionModel = getConsumptionTransactionModel();
  const InterviewLogModel = getInterviewLogModel();
  const InterviewModel = getInterviewModel();
  const JobBidModel = getJobBidModel();
  const MarketplaceCallerProfileModel = getMarketplaceCallerProfileModel();
  const MarketplaceInterviewOpportunityModel = getMarketplaceInterviewOpportunityModel();
  const MarketplaceMatchModel = getMarketplaceMatchModel();
  const MarketplaceParticipantModel = getMarketplaceParticipantModel();
  const ProfileShareRequestModel = getProfileShareRequestModel();
  const TailoredResumeModel = getTailoredResumeModel();
  const TeamConsumptionModel = getTeamConsumptionModel();

  if (BidProfileModel.associations.user) return;

  WebUserModel.hasMany(BidProfileModel, { foreignKey: 'userId', as: 'bidProfiles' });
  BidProfileModel.belongsTo(WebUserModel, { foreignKey: 'userId', as: 'user' });
  WebUserModel.hasMany(FaqModel, { foreignKey: 'createdByUserId', as: 'faqs' });
  FaqModel.belongsTo(WebUserModel, { foreignKey: 'createdByUserId', as: 'createdBy' });
  WebUserModel.hasMany(TeamConsumptionModel, { foreignKey: 'createdByUserId', as: 'consumptionRecords' });
  TeamConsumptionModel.belongsTo(WebUserModel, { foreignKey: 'createdByUserId', as: 'createdBy' });
  WebUserModel.hasMany(ConsumptionTransactionModel, { foreignKey: 'createdByUserId', as: 'consumptionTransactions' });
  ConsumptionTransactionModel.belongsTo(WebUserModel, { foreignKey: 'createdByUserId', as: 'createdBy' });
  WebUserModel.hasMany(ConsumptionTransactionModel, { foreignKey: 'spentByUserId', as: 'spentConsumptionTransactions' });
  ConsumptionTransactionModel.belongsTo(WebUserModel, { foreignKey: 'spentByUserId', as: 'spentByUser' });
  ConsumptionTransactionModel.hasMany(ConsumptionLedgerEntryModel, { foreignKey: 'transactionId', as: 'entries', onDelete: 'CASCADE' });
  ConsumptionLedgerEntryModel.belongsTo(ConsumptionTransactionModel, { foreignKey: 'transactionId', as: 'transaction' });
  ConsumptionAccountModel.hasMany(ConsumptionLedgerEntryModel, { foreignKey: 'accountId', as: 'entries' });
  ConsumptionLedgerEntryModel.belongsTo(ConsumptionAccountModel, { foreignKey: 'accountId', as: 'account' });
  WebUserModel.hasOne(MarketplaceParticipantModel, { foreignKey: 'userId', as: 'marketplaceParticipant' });
  MarketplaceParticipantModel.belongsTo(WebUserModel, { foreignKey: 'userId', as: 'user' });
  MarketplaceParticipantModel.belongsTo(WebUserModel, { foreignKey: 'reviewedByUserId', as: 'reviewedBy' });
  WebUserModel.hasMany(MarketplaceInterviewOpportunityModel, { foreignKey: 'ownerUserId', as: 'marketplaceInterviewOpportunities' });
  MarketplaceInterviewOpportunityModel.belongsTo(WebUserModel, { foreignKey: 'ownerUserId', as: 'owner' });
  MarketplaceInterviewOpportunityModel.belongsTo(WebUserModel, { foreignKey: 'reviewedByUserId', as: 'reviewedBy' });
  WebUserModel.hasMany(MarketplaceCallerProfileModel, { foreignKey: 'ownerUserId', as: 'marketplaceCallerProfiles' });
  MarketplaceCallerProfileModel.belongsTo(WebUserModel, { foreignKey: 'ownerUserId', as: 'owner' });
  MarketplaceCallerProfileModel.belongsTo(WebUserModel, { foreignKey: 'reviewedByUserId', as: 'reviewedBy' });
  MarketplaceInterviewOpportunityModel.hasMany(MarketplaceMatchModel, { foreignKey: 'interviewOpportunityId', as: 'matches' });
  MarketplaceMatchModel.belongsTo(MarketplaceInterviewOpportunityModel, { foreignKey: 'interviewOpportunityId', as: 'interviewOpportunity' });
  MarketplaceCallerProfileModel.hasMany(MarketplaceMatchModel, { foreignKey: 'callerProfileId', as: 'matches' });
  MarketplaceMatchModel.belongsTo(MarketplaceCallerProfileModel, { foreignKey: 'callerProfileId', as: 'callerProfile' });
  MarketplaceMatchModel.belongsTo(WebUserModel, { foreignKey: 'assignedInternalUserId', as: 'assignedInternalUser' });
  BidProfileModel.hasMany(JobBidModel, { foreignKey: 'profileId', as: 'bids' });
  JobBidModel.belongsTo(BidProfileModel, { foreignKey: 'profileId', as: 'profile' });
  BidProfileModel.hasMany(AssessmentModel, { foreignKey: 'profileId', as: 'assessments' });
  AssessmentModel.belongsTo(BidProfileModel, { foreignKey: 'profileId', as: 'profile' });
  WebUserModel.hasMany(AssessmentModel, { foreignKey: 'userId', as: 'createdAssessments' });
  AssessmentModel.belongsTo(WebUserModel, { foreignKey: 'userId', as: 'createdBy' });
  ScrapedJobModel.hasMany(AssessmentModel, { foreignKey: 'jobId', as: 'assessments' });
  AssessmentModel.belongsTo(ScrapedJobModel, { foreignKey: 'jobId', as: 'job' });
  BidProfileModel.hasMany(InterviewModel, { foreignKey: 'profileId', as: 'interviews' });
  InterviewModel.belongsTo(BidProfileModel, { foreignKey: 'profileId', as: 'profile' });
  InterviewModel.hasMany(InterviewLogModel, { foreignKey: 'interviewId', as: 'logs' });
  InterviewLogModel.belongsTo(InterviewModel, { foreignKey: 'interviewId', as: 'interview' });
  BidProfileModel.hasMany(TailoredResumeModel, { foreignKey: 'profileId', as: 'tailoredResumes' });
  TailoredResumeModel.belongsTo(BidProfileModel, { foreignKey: 'profileId', as: 'profile' });
  BidProfileModel.hasMany(ProfileShareRequestModel, { foreignKey: 'profileId', as: 'shareRequests' });
  ProfileShareRequestModel.belongsTo(BidProfileModel, { foreignKey: 'profileId', as: 'profile' });
  WebUserModel.hasMany(ProfileShareRequestModel, { foreignKey: 'ownerUserId', as: 'sentProfileShares' });
  WebUserModel.hasMany(ProfileShareRequestModel, { foreignKey: 'recipientUserId', as: 'receivedProfileShares' });
  ProfileShareRequestModel.belongsTo(WebUserModel, { foreignKey: 'ownerUserId', as: 'owner' });
  ProfileShareRequestModel.belongsTo(WebUserModel, { foreignKey: 'recipientUserId', as: 'recipient' });
  ScrapedJobModel.hasMany(JobBidModel, { foreignKey: 'jobId', as: 'bids' });
  JobBidModel.belongsTo(ScrapedJobModel, { foreignKey: 'jobId', as: 'job' });
  ScrapedJobModel.hasMany(InterviewModel, { foreignKey: 'jobId', as: 'interviews' });
  InterviewModel.belongsTo(ScrapedJobModel, { foreignKey: 'jobId', as: 'job' });
  JobBidModel.hasOne(InterviewModel, { foreignKey: 'jobBidId', as: 'interview' });
  InterviewModel.belongsTo(JobBidModel, { foreignKey: 'jobBidId', as: 'bid' });
}
